version: '3'
services:
  common-service:
    image: common:latest
    container_name: "common-service"
    ports:
      - "8081:8081"
  nginx:
    image: nginx:stable
    container_name: nginx-common
    restart: "no"
    ports:
      - '8082:80'
    volumes:
      - /Users/hongxiao/IdeaProjects/docker-compose-files-main/inter/ng/nginx.conf:/etc/nginx/nginx.conf