version: '3'
services:
  jenkins:
    container_name: 'jenkins-arm'
    image: 'jenkins/jenkins:jdk11'
    ports:
      - "18080:8080"
    volumes:
      - '/Users/hongxiao/IdeaProjects/docker-compose-files-main/inter/jenkins:/var/jenkins_home'
      - '/Users/hongxiao/IdeaProjects/docker-compose-files-main/inter/jenkins/html:/usr/share/jenkins/html'
      - '/var/run/docker.sock:/var/run/docker.sock'
  nginx:
    container_name: 'nginx-inter'
    depends_on:
      - jenkins
    image: nginx:stable
    volumes:
      - '/Users/hongxiao/IdeaProjects/docker-compose-files-main/inter/ng/html:/usr/xh/html'
      - '/Users/hongxiao/IdeaProjects/docker-compose-files-main/inter/ng/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "80:80"
      - "443:443"
    restart: always