version: '3.1'
services:
  kibana-arm:
    image: gagara/kibana-oss-arm64:7.6.2
    container_name: kibana-arm
    restart: "no"
    volumes:
      - /Users/hongxiao/IdeaProjects/docker-compose-files-main/kibana/kibana.yaml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    network_mode: "bridge"