version: '3'
services:
   redis:
     image: redis:latest
     restart: "no"
     container_name: redis
     ports:
       - "6379:6379"
     volumes:
       - /Users/hongxiao/docker-volumes/redis-standalone/redis.conf:/etc/redis/redis.conf
       - /Users/hongxiao/docker-volumes/redis-standalone/data:/data
     command: redis-server /etc/redis/redis.conf
     privileged: true