version: '3.4'
services:
  oap-amd:
    image: apache/skywalking-oap-server:8.9.0
    container_name: oap-amd
    hostname: oap-amd
    restart: "no"
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:19200
      JAVA_OPTS: "-Xms1024m -Xmx1024m"
    networks:
      - es-net

  ui-amd:
    image: apache/skywalking-ui:8.9.0
    container_name: skywalking-amd-ui
    depends_on:
      - oap-amd
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      SW_OAP_ADDRESS: http://oap-amd:12800
      TZ: Asia/Shanghai
    networks:
      - es-net
networks:
  es-net:
    external: trueTokenProvider