version: '3.4'
services:
  oap:
    image: apache/skywalking-oap-server:8.9.0
    container_name: oap
    restart: "no"
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      JAVA_OPTS: "-Xms1024m -Xmx1024m"

  ui:
    image: apache/skywalking-ui:8.9.0
    container_name: skywalking-ui
    depends_on:
      - oap
    links:
      - oap
    restart: "no"
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: http://oap:12800
      TZ: Asia/Shanghai