version: '3.3'
services:
  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:7.17.1
    container_name: elasticsearch
    restart: "no"
    ports:
      - 19200:19200
      - 19300:19300
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - es-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /Users/hongxiao/docker-volumes/elasticsearch/data:/usr/share/elasticsearch/data
      - /Users/hongxiao/docker-volumes/elasticsearch/log:/usr/share/elasticsearch/logs
      - /Users/hongxiao/IdeaProjects/docker-compose-files-main/elasticsearch/arm/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  es-head:
    image: lyws365/elasticsearch-head:arm64
    container_name: es-head
    ports:
      - 9100:9100
    links:
      - elasticsearch

networks:
  es-net:
    external: true