version: '3.0'
services:
  minio:
    image: minio/minio:RELEASE.2023-08-04T17-40-21Z
    container_name: minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - /Users/hongxiao/docker-volumes/minio:/data
