version: '2'
services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - /Users/hongxiao/docker-volumes/kafka/zk/logs:/datalog
      - /Users/hongxiao/docker-volumes/kafka/zk/data:/data
      - /Users/hongxiao/docker-volumes/kafka/zk/conf:/conf
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: "/kafka/KafkaLog"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/hongxiao/docker-volumes/kafka/kafkalogs:/kafka/KafkaLog
