version: '3'

x-kraft: &kraft-config
  ALLOW_PLAINTEXT_LISTENER: "yes"
  # 允许使用Kraft
  KAFKA_ENABLE_KRAFT: "yes"
  KAFKA_CFG_PROCESS_ROLES: broker,controller
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_BROKER_LISTENER_NAMES: BROKER
  # 定义kafka服务端socket监听端口（Docker内部的ip地址和端口）
  KAFKA_CFG_LISTENERS: BROKER://:9092,CONTROLLER://:9093
  # 定义安全协议
  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
  KAFKA_KRAFT_CLUSTER_ID: iZWRiSqjZAlYwlKEqHFQWI
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft1:9093,2@kafka-kraft2:9093,3@kafka-kraft3:9093
  # 设置broker最大内存，和初始内存
  KAFKA_HEAP_OPTS: -Xmx512M -Xms256M

services:
  kafka-kraft1:
    container_name: kafka-kraft1
    image: blacktop/kafka:3.3.1
    ports:
      - "19092:9092"
    environment:
      <<: *kraft-config
      #定义外网访问地址（宿主机ip地址和端口）
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://:19092
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: "/kafka/KafkaLog"
    networks:
      - netkafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/hongxiao/docker-volumes/kafka/kraft1/kafkalogs:/kafka/KafkaLog
  kafka-kraft2:
    container_name:  kafka-kraft2
    image: blacktop/kafka:3.3.1
    ports:
      - "29092:9092"
    environment:
      <<: *kraft-config
      #定义外网访问地址（宿主机ip地址和端口）
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://:29092
      KAFKA_BROKER_ID: 2
      KAFKA_LOG_DIRS: "/kafka/KafkaLog"
    networks:
      - netkafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/hongxiao/docker-volumes/kafka/kraft2/kafkalogs:/kafka/KafkaLog
  kafka-kraft3:
    container_name:  kafka-kraft3
    image: blacktop/kafka:3.3.1
    ports:
      - "39092:9092"
    environment:
      <<: *kraft-config
      #定义外网访问地址（宿主机ip地址和端口）
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://:39092
      KAFKA_BROKER_ID: 3
      KAFKA_LOG_DIRS: "/kafka/KafkaLog"
    networks:
      - netkafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/hongxiao/docker-volumes/kafka/kraft3/kafkalogs:/kafka/KafkaLog
  kafka-kraft4:
    container_name:  kafka-kraft4
    image: blacktop/kafka:3.3.1
    ports:
      - "49092:9092"
    environment:
      <<: *kraft-config
      KAFKA_CFG_PROCESS_ROLES: broker
      #定义外网访问地址（宿主机ip地址和端口）
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://:49092
      KAFKA_BROKER_ID: 4
      KAFKA_LOG_DIRS: "/kafka/KafkaLog"
    networks:
      - netkafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/hongxiao/docker-volumes/kafka/kraft4/kafkalogs:/kafka/KafkaLog

networks:
  netkafka:
    external: true